version: '3'
services:
  app:
    build: ./docker
    container_name: zk-voting-app
    image: zk-voting-app
    volumes:
      - ./contracts:/app/contracts
      - ./ui:/app/ui
    ports:
      - 3000:3000
